POST http://localhost:5000/recognition
Content-Type: text/plain

/91j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAyAMgDASIA
AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA
AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3
ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm
p6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA
AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx
BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK
U1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3
uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDU8L+G
NAuPCejTTaHpkksljA7u9pGWZjGCSSRyTWuPCXhv/oXtJ/8AAKP/AApvhL/kTdD/AOwfb/8Aota2
xQBkDwj4a/6F7Sf/AACj/wDiacPCPhr/AKF3Sf8AwCj/APia1xThQBkDwh4Z/wChd0n/AMAo/wD4
mnDwf4Z/6F3SP/AKP/4mtCO+s5bySzjuoHuo13PCsgLqPUr1ArkfE/xS0PwzqDWDrLd3Sf6xIMYQ
+hJ70AdAPB/hj/oXNI/8AY//AImnDwd4Y/6FzSP/AABi/wDiaw/D/wAUfDOvyLAlzJaXLcCK5Xbk
+xGR+tduvIyOlAGMPB3hj/oW9I/8AYv/AImnDwb4X/6FvR//AABi/wDia0r28g06wuL25fZBBG0s
jeiqMn9BXBaZ8YNIvdaGmTW7wyb2VpS4KDaMnnvzkD1xxyQCAdaPBvhf/oW9H/8AAGL/AOJp48Ge
Fv8AoWtH/wDAGL/4mtkVFeXcVjZy3UzBY4kLMT7UAZo8GeFv+ha0b/wBi/8AiacPBfhX/oWdG/8A
ACL/AOJrz3VPjHcpqLadpejie4jcJKzO67CevDouMerbee1dt4L1LV9VsmutSR1jORF5m3c2GIyd
oCkfLkEdQQe4NAF4eC/Cv/Qs6N/4ARf/ABNOHgrwp/0LOjf+AEX/AMTVy91nTdNXN7fQQD/bcCsW
6+I3he0nSFtTiZ2K52nhMsV+Y9sFcH0yKANAeCfCn/QsaL/4ARf/ABNOHgnwp/0LGi/+AEX/AMTV
zRdXtNe0m31OxffazrujYjGecHj1BBH4VpCgDDHgjwn/ANCvov8A4ARf/E04eCPCf/Qr6L/4L4v/
AImtLUNSstIsZL7ULqK2tY8b5ZW2quSAMn6kCqui+J9F8RPcpo+ow3pttvmmEkhd2cc9D909PSgC
EeB/CX/Qr6J/4L4v/iacPA/hL/oVtE/8F8X/AMTW6KcKAMIeBvCP/QraJ/4L4v8A4mnDwN4R/wCh
V0T/AMF8X/xNbop4oA4bxl4M8LWvgbxBcW/hrR4Z4tNuXjkjsYlZGETEEELkEHvRW545/wCSe+Jf
+wVdf+imooA47wl/yJuh/wDYPt//AEWtbQrF8I/8iZof/YPt/wD0WtbYoA53xv4mTwp4ZuL4FTdN
+6tkPO6Q9OPQck/SuS0vRvHHjbTLe81jxAdM0+dAy29nHtkdT3bGMZHPU/StHxZ4J1PxV400ue7l
hbQLYZaIMQwPUgjvuIAyOgH5+hIoVQqgBQMADtQB5zqXw68L+G/DV7qEUN39rtomkW7+1Osu7sfl
IHX2rxbRYYbvUG1LVW8+zgnje8Dud7o7YYjuT3r6N8fwvP4C1mNASxtyQPoQa8A8EeHdO8Q6jcRa
rqiafaRRhjI0ipuJOAAW460AeqSfC3wlrqw3/hu/WPY6sfJm82NuckEckH/OK9WVQqhQMADAFfJ+
latqPgvXEubO7BKSMkiI+VcKxUhh74yPrXvcnxT8LQ6QLs6pC1wYg/2dclt2Pu8CgDF+JWrXmr6t
B4L0ohpbxFMzZwI/myMn0IHT3ryzwfbw23j+O3i3zPDKRAh48yRSCM47cE/hXVeCfGuhaVe6lr+u
3FxLqN037uNYGbaoJxhsY7461xnhvVodO8fwaukU1xDFcPNsQAOynPqcd6APq9nS2t2klkxHGmWd
j0AHJNeW/EXxppeoeHrqzsr2HcvDhztfOM4UHuBjnrzgY5I3V8Y6xqVpIn/CCanJDIGRgZ4gGU8H
qa8q8ZeH/JW4vJfCuoWk8is7z3V9GwXOApwvYdKAK3w61i/0u1vrey0+a5kuyu8xkMQg7+WRggk4
3fXFehal4z1bQPDc0V3bvbzN5hjcZVFG7kKW785UegI7Cuf+EuraxFpMw0vwsNXe3kwbg3sULR7l
xt+YZIwBj0xR8VbzxNqGnltS8NppkO1dz/bVnyqtwPlAAO5j+f40Acd4f8K63491QyyXW0S/MZpG
JHJIwB6ZBr0+1+AelR22LjU5pJz/ABLgKOR2/OvI/C8fiy6DWPh9rhRN18tggPOOGPvVrXLTxx4R
uYpdWnvoHdvlc3HmBiOcZBI7dKAPqTw/odt4c0eHTLN5Gtoc7PMbJAPPX65P1Jrz7xp8aLbwxrr6
XZ6eL14DiZjJtAPoODWX8P8AX/HPi3RxBBq+mWyorKJJ7Z5JXAIDN97HVhXlFppc3iL4jjTNQuj5
9zetDJOqAZbJGcdB0oA9R8d/ELTPGnwjvJLLdDci5hSe2c5ZPmyDnuOOtRfAfV9I0PQNbutU1K0s
hJcRqDPMqFtqk8Ann73asj4m/Cqz8HeHI9U0u8vJk80JcrOVxz90gKoxz9a2vgBoukalpmq3N7pt
pdXUFwgjknhV2QFe2RxyDQBv+Lfjtoel2/leH/8AiZ3bdHKMkSfiQC34ce9cEv7QPi6NGzZ6YQ/3
XkhfK/TDAGuL8R3J1r4i3jXZ2pLf+Uw6bUD7cD0AAr63h8MaIuippTaZaSWYQKY3hVlbjr0oA5D4
Y6xfeLEfXJ/Fc9+sWYpLBbFbeOJyAevJb2Oa9KFcz4R8Fad4M/tGPS2cW15OJhE/PlHGCAfSunFA
GD45/wCSe+Jf+wVdf+imopfHX/JPfEv/AGCrr/0U1FAHHeEf+RM0L/sH2/8A6LWtoVi+Ef8AkTNC
/wCwfb/+i1rbFADhXOeMPG2m+D7DzLlhNeSD9xao2Gf3Povv/Osjx18RIfDJ/szTovtetSgBIgCV
iz0LY6k9lH/68rwd8N7i5vv+Ej8Yu13qMp8xLaU7gnoX7E+i9B+gAEt734ieOtLURW1joum3CYea
RSXlUjkqpycHtwPrXm0uhw+CfGcdt4n01r7TlY8qWQSL2dcHtwcZ9q+nhVHV9D0zXrM2mp2cdxEe
m8cqfUHqDQB81+OJvDM17G/hliYZHeWRTD5YjLBQEHGcDaT/AMCOK9O0zw7c698CYNOtLeM38oBj
Y4Xdibdyf93ipJPgXohvhLDqN4lvuyYXCsfpuwOPw/GvT7Cyg06xhs7ZAkMKhUUdhQB4xpHwHuJE
D6xqqRtj/V267sdf4jj/AGe3rXnGq6Ctl4vk0aKXyj5oRfNODGx6Ix9iQN3TvX1yK5/U/BGh6tP9
pntAt3vDi4Q4cEE9+/BI57fQUAP8F6RdaL4dt7W8ZTOFXcA27ado3Dd3y29v+BEVm/E+ze48H3Uy
PtMMbNnyixzjjDDlfTuCCQcZyOwgiSCGOGPOxFCrlixwPc8n8ao+INFh8QaFdaZOdqTrt37QSvuM
gjNAHkn7Pd182u2hPJEMij6bwf5ivTfHXhlPFHhe5tAim5RTJbsVyVcA9PcjIz2zmmeFPBVh4YeS
5t1KXM6bZ8bCrcjGNqLjGOgAHJ4711IoA+Y/hjrFv4d8V/YdZLQKJQG80nCYydoHYlxG2fRCOc8d
l8bdZ0q90q3t7S7ilm3lyYnD8r8oBHYEO/PXKiun8d/CjT/FlydRtX+yagR87KPlk9yPXoM1zmgf
Aj7NqMU+q6gJYkw22McltvI54xuOf+A+9AGz8ENEuLDw613cIwWdA0QcHK7iSxU/3Soi/FTXm/xE
0u68C/E+LWoIs273CXkB6BmBBce3zbvwNfS9pawWVrFbW0YjhiUIijsAMD9BVLX/AA7pnifS5NP1
S3EsL9D0ZD6qexoA8u+J3jrw/wCIfhU6WN/DLc3bxYgDDzIyGDHcvbpj8az/ANnC6Al8Q2ZPJWCV
R9N4P81rWh/Z/wBKtnvXXU5rjzLeSO3SZABG7KQrEjrgkHoOlanwx+FV94E1e51G71aG4M9uYDBD
EQPvK27cT2xjGO9AHmnxZ+HOqaN4kvNb0+2kn026k8/dEuTCx5YHHvk59663wF8dtPj02303xSJY
ZoVEa3qIXVwOBuA5B+gNe4FQylWAIPUEda4zxH8JvCPiZmluNPNrct/y3tH8tvy5U/iKANjw7428
P+Kbue20a/W6kgRZJNqkAAnHfr/9eujFedeAvhTbeA9dudQtNUnuUngMJikQDHzKQcjv8v616KKA
MHx1/wAk98S/9gq6/wDRTUUvjr/knviX/sFXX/opqKAPjeHxR4gt4Y4Ydd1OKKNQiIl3IqqoGAAA
eAKk/wCEu8S/9DDq3/gbJ/8AFUUUAVZNc1eW/jv5NVvnvIxtS4a4cyKOeA2cgcn86tf8Jf4m/wCh
i1f/AMDZP/iqKKAF/wCEw8Tf9DHq/wD4Gyf/ABVH/CYeJ/8AoY9X/wDA6T/4qiigA/4THxP/ANDH
q/8A4HS//FUv/CY+KP8AoZNY/wDA6X/4qiigA/4TLxR/0Mmsf+B0v/xVH/CZeKf+hl1j/wADpf8A
4qiigA/4TPxT/wBDLrH/AIHS/wDxVL/wmfin/oZdZ/8AA+X/AOKoooAP+E08Vf8AQzaz/wCB8v8A
8VR/wmnir/oZtZ/8D5f/AIqiigBf+E18V/8AQzaz/wCB8v8A8VR/wm3iv/oZ9a/8D5f/AIqiigA/
4TbxZ/0M+tf+B8v/AMVS/wDCb+LP+ho1r/wPl/8AiqKKAD/hN/Fv/Q0a3/4MJf8A4qj/AITjxb/0
NGt/+DCX/wCKoooAP+E48W/9DTrf/gwl/wDiqX/hOfF3/Q063/4MJf8A4qiigA/4Tnxd/wBDVrn/
AIMJf/iqP+E68X/9DVrn/gwl/wDiqKKAGT+M/FN1by29x4l1maCVCkkcl9KyupGCCC2CCOMUUUUA
f//Z


